# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.openai.container_file_citation_body import ContainerFileCitationBody
from models.openai.file_citation_body import FileCitationBody
from models.openai.file_path import FilePath
from models.openai.url_citation_body import UrlCitationBody
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


Annotation = Union[
    FileCitationBody, UrlCitationBody, ContainerFileCitationBody, FilePath
]
