# Code generated by schema2code at 2026-02-23 18:45:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .admin_api_key import AdminApiKey
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ApiKeyList(BaseModel):
    data: Annotated[Optional[List[AdminApiKey]], Field(default=None)] = None
    first_id: Annotated[Optional[str], Field(default=None)] = None
    has_more: Annotated[Optional[bool], Field(default=None)] = None
    last_id: Annotated[Optional[str], Field(default=None)] = None
    object: Annotated[Optional[str], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")