# Code generated by schema2code at 2026-02-23 18:45:48. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ApplyPatchToolParam(BaseModel):
    """Allows the assistant to create, delete, or update files using unified diffs."""
    type: Annotated[Literal["apply_patch"], Field(default='apply_patch', description="The type of the tool. Always `apply_patch`.")]
    """The type of the tool. Always `apply_patch`."""

    model_config = ConfigDict(extra="ignore")