# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, constr

# No relative imports - file only imports from enum and pydantic



class ApplyPatchCallOutputStatus(str, Enum):
    COMPLETED = 'completed'
    FAILED = 'failed'