# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ApplyPatchUpdateFileOperation(BaseModel):
    """Instruction describing how to update a file via the apply_patch tool."""
    diff: Annotated[str, Field(..., description="Diff to apply.")]
    """Diff to apply."""
    path: Annotated[str, Field(..., description="Path of the file to update.")]
    """Path of the file to update."""
    type: Annotated[Literal["update_file"], Field(default='update_file', description="Update an existing file with the provided diff.")]
    """Update an existing file with the provided diff."""

    model_config = ConfigDict(extra="ignore")