# Code generated by schema2code at 2026-02-23 18:45:15. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class AuditLogActorServiceAccount(BaseModel):
    """The service account that performed the audit logged action."""
    id: Annotated[Optional[str], Field(default=None, description="The service account id.")] = None
    """The service account id."""

    model_config = ConfigDict(extra="ignore")