# Code generated by schema2code at 2026-02-23 18:45:03. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ChatSessionHistory(BaseModel):
    """History retention preferences returned for the session."""
    enabled: Annotated[bool, Field(..., description="Indicates if chat history is persisted for the session.")]
    """Indicates if chat history is persisted for the session."""
    recent_threads: Annotated[Union[int, Any], Field(...)]

    model_config = ConfigDict(extra="ignore")