# Code generated by schema2code at 2026-02-23 18:45:06. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .chat_completion_message_custom_tool_call import ChatCompletionMessageCustomToolCall
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
from .chat_completion_message_tool_calls import ChatCompletionMessageToolCalls
from .chat_completion_request_assistant_message import ChatCompletionRequestAssistantMessage
from .chat_completion_request_assistant_message_content_part import ChatCompletionRequestAssistantMessageContentPart
from .chat_completion_request_developer_message import ChatCompletionRequestDeveloperMessage
from .chat_completion_request_function_message import ChatCompletionRequestFunctionMessage
from .chat_completion_request_message_content_part_audio import ChatCompletionRequestMessageContentPartAudio
from .chat_completion_request_message_content_part_file import ChatCompletionRequestMessageContentPartFile
from .chat_completion_request_message_content_part_image import ChatCompletionRequestMessageContentPartImage
from .chat_completion_request_message_content_part_refusal import ChatCompletionRequestMessageContentPartRefusal
from .chat_completion_request_message_content_part_text import ChatCompletionRequestMessageContentPartText
from .chat_completion_request_system_message import ChatCompletionRequestSystemMessage
from .chat_completion_request_system_message_content_part import ChatCompletionRequestSystemMessageContentPart
from .chat_completion_request_tool_message import ChatCompletionRequestToolMessage
from .chat_completion_request_tool_message_content_part import ChatCompletionRequestToolMessageContentPart
from .chat_completion_request_user_message import ChatCompletionRequestUserMessage
from .chat_completion_request_user_message_content_part import ChatCompletionRequestUserMessageContentPart
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Audio(BaseModel):
    """Data about a previous audio response from the model.
[Learn more](https://platform.openai.com/docs/guides/audio).
"""
    id: Annotated[str, Field(..., description="Unique identifier for a previous audio response from the model. ")]
    """Unique identifier for a previous audio response from the model. """

    model_config = ConfigDict(extra="ignore")

class FunctionCall(BaseModel):
    """Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model."""
    arguments: Annotated[str, Field(..., description="The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.")]
    """The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function."""
    name: Annotated[str, Field(..., description="The name of the function to call.")]
    """The name of the function to call."""

    model_config = ConfigDict(extra="ignore")

ChatCompletionRequestMessage = Union[ChatCompletionRequestDeveloperMessage, ChatCompletionRequestSystemMessage, ChatCompletionRequestUserMessage, ChatCompletionRequestAssistantMessage, ChatCompletionRequestToolMessage, ChatCompletionRequestFunctionMessage]