# Code generated by schema2code at 2026-02-23 18:45:03. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ChatSessionAutomaticThreadTitling(BaseModel):
    """Automatic thread title preferences for the session."""
    enabled: Annotated[bool, Field(..., description="Whether automatic thread titling is enabled.")]
    """Whether automatic thread titling is enabled."""

    model_config = ConfigDict(extra="ignore")