# Code generated by schema2code at 2026-02-23 18:45:03. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ChatSessionFileUpload(BaseModel):
    """Upload permissions and limits applied to the session."""
    enabled: Annotated[bool, Field(..., description="Indicates if uploads are enabled for the session.")]
    """Indicates if uploads are enabled for the session."""
    max_file_size: Annotated[Union[int, Any], Field(...)]
    max_files: Annotated[Union[int, Any], Field(...)]

    model_config = ConfigDict(extra="ignore")