# Code generated by schema2code at 2026-02-23 18:45:11. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .chat_completion_message_custom_tool_call import ChatCompletionMessageCustomToolCall
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, RootModel, conint, confloat



ChatCompletionMessageToolCalls = RootModel[
    List[Union[ChatCompletionMessageToolCall, ChatCompletionMessageCustomToolCall]]
]
"""The tool calls generated by the model, such as function calls."""