# Code generated by schema2code at 2026-02-23 18:45:11. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Custom(BaseModel):
    """The custom tool that the model called."""
    input: Annotated[str, Field(..., description="The input for the custom tool call generated by the model.")]
    """The input for the custom tool call generated by the model."""
    name: Annotated[str, Field(..., description="The name of the custom tool to call.")]
    """The name of the custom tool to call."""

    model_config = ConfigDict(extra="ignore")

class ChatCompletionMessageCustomToolCall(BaseModel):
    """A call to a custom tool created by the model.
"""
    custom: Annotated[Custom, Field(..., description="The custom tool that the model called.")]
    """The custom tool that the model called."""
    id: Annotated[str, Field(..., description="The ID of the tool call.")]
    """The ID of the tool call."""
    type: Annotated[Literal["custom"], Field(..., description="The type of the tool. Always `custom`.")]
    """The type of the tool. Always `custom`."""

    model_config = ConfigDict(extra="ignore")

ChatCompletionMessageCustomToolCall.model_rebuild()