# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

# No relative imports - file only imports from pydantic



class CodeInterpreterOutputImage(BaseModel):
    """The image output from the code interpreter."""
    type: Annotated[Literal["image"], Field(default='image', description="The type of the output. Always `image`.")]
    """The type of the output. Always `image`."""
    url: Annotated[str, Field(..., description="The URL of the image output from the code interpreter.")]
    """The URL of the image output from the code interpreter."""

    model_config = ConfigDict(extra="ignore")