# Code generated by schema2code at 2026-02-23 18:45:05. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .embedding import Embedding
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Usage(BaseModel):
    """The usage information for the request."""
    prompt_tokens: Annotated[int, Field(..., description="The number of tokens used by the prompt.")]
    """The number of tokens used by the prompt."""
    total_tokens: Annotated[int, Field(..., description="The total number of tokens used by the request.")]
    """The total number of tokens used by the request."""

    model_config = ConfigDict(extra="ignore")

class CreateEmbeddingResponse(BaseModel):
    data: Annotated[List[Embedding], Field(..., description="The list of embeddings generated by the model.")]
    """The list of embeddings generated by the model."""
    model: Annotated[str, Field(..., description="The name of the model used to generate the embedding.")]
    """The name of the model used to generate the embedding."""
    object: Annotated[Literal["list"], Field(..., description="The object type, which is always \"list\".")]
    """The object type, which is always \"list\"."""
    usage: Annotated[Usage, Field(..., description="The usage information for the request.")]
    """The usage information for the request."""

    model_config = ConfigDict(extra="ignore")

CreateEmbeddingResponse.model_rebuild()