# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

# No relative imports - file only imports from pydantic



class FilePath(BaseModel):
    """A path to a file.
"""
    file_id: Annotated[str, Field(..., description="The ID of the file. ")]
    """The ID of the file. """
    index: Annotated[int, Field(..., description="The index of the file in the list of files. ")]
    """The index of the file in the list of files. """
    type: Annotated[Literal["file_path"], Field(..., description="The type of the file path. Always `file_path`. ")]
    """The type of the file path. Always `file_path`. """

    model_config = ConfigDict(extra="ignore")