# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .function_shell_call_output_exit_outcome import FunctionShellCallOutputExitOutcome
from .function_shell_call_output_timeout_outcome import FunctionShellCallOutputTimeoutOutcome
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class FunctionShellCallOutputContent(BaseModel):
    """The content of a shell tool call output that was emitted."""
    created_by: Annotated[Optional[str], Field(default=None, description="The identifier of the actor that created the item.")] = None
    """The identifier of the actor that created the item."""
    outcome: Annotated[Union[FunctionShellCallOutputTimeoutOutcome, FunctionShellCallOutputExitOutcome], Field(..., description="Represents either an exit outcome (with an exit code) or a timeout outcome for a shell call output chunk.")]
    """Represents either an exit outcome (with an exit code) or a timeout outcome for a shell call output chunk."""
    stderr: Annotated[str, Field(..., description="The standard error output that was captured.")]
    """The standard error output that was captured."""
    stdout: Annotated[str, Field(..., description="The standard output that was captured.")]
    """The standard output that was captured."""

    model_config = ConfigDict(extra="ignore")