# Code generated by schema2code at 2026-02-23 18:45:13. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class GroupUserAssignment(BaseModel):
    """Confirmation payload returned after adding a user to a group."""
    group_id: Annotated[str, Field(..., description="Identifier of the group the user was added to.")]
    """Identifier of the group the user was added to."""
    object: Annotated[Literal["group.user"], Field(..., description="Always `group.user`.")]
    """Always `group.user`."""
    user_id: Annotated[str, Field(..., description="Identifier of the user that was added.")]
    """Identifier of the user that was added."""

    model_config = ConfigDict(extra="ignore")