# Code generated by schema2code at 2026-02-23 18:45:13. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class GroupUserDeletedResource(BaseModel):
    """Confirmation payload returned after removing a user from a group."""
    deleted: Annotated[bool, Field(..., description="Whether the group membership was removed.")]
    """Whether the group membership was removed."""
    object: Annotated[Literal["group.user.deleted"], Field(..., description="Always `group.user.deleted`.")]
    """Always `group.user.deleted`."""

    model_config = ConfigDict(extra="ignore")