# Code generated by schema2code at 2026-02-23 18:45:13. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .group import Group
from .role import Role
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class GroupRoleAssignment(BaseModel):
    """Role assignment linking a group to a role."""
    group: Annotated[Group, Field(...)]
    object: Annotated[Literal["group.role"], Field(..., description="Always `group.role`.")]
    """Always `group.role`."""
    role: Annotated[Role, Field(...)]

    model_config = ConfigDict(extra="ignore")