# Code generated by schema2code at 2026-02-23 18:45:13. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Group(BaseModel):
    """Summary information about a group returned in role assignment responses."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) when the group was created.")]
    """Unix timestamp (in seconds) when the group was created."""
    id: Annotated[str, Field(..., description="Identifier for the group.")]
    """Identifier for the group."""
    name: Annotated[str, Field(..., description="Display name of the group.")]
    """Display name of the group."""
    object: Annotated[Literal["group"], Field(..., description="Always `group`.")]
    """Always `group`."""
    scim_managed: Annotated[bool, Field(..., description="Whether the group is managed through SCIM.")]
    """Whether the group is managed through SCIM."""

    model_config = ConfigDict(extra="ignore")