# Code generated by schema2code at 2026-02-23 18:45:16. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .fine_tuning_job_event import FineTuningJobEvent
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ListFineTuningJobEventsResponse(BaseModel):
    data: Annotated[List[FineTuningJobEvent], Field(...)]
    has_more: Annotated[bool, Field(...)]
    object: Annotated[Literal["list"], Field(...)]

    model_config = ConfigDict(extra="ignore")