# Code generated by schema2code at 2026-02-23 18:45:18. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ImageUrl(BaseModel):
    """Contains either an image URL or a data URL for a base64 encoded image."""
    url: Annotated[AnyUrl, Field(..., description="Either a URL of the image or the base64 encoded image data.")]
    """Either a URL of the image or the base64 encoded image data."""

    model_config = ConfigDict(extra="ignore")

class ModerationImageURLInput(BaseModel):
    """An object describing an image to classify."""
    image_url: Annotated[ImageUrl, Field(..., description="Contains either an image URL or a data URL for a base64 encoded image.")]
    """Contains either an image URL or a data URL for a base64 encoded image."""
    type: Annotated[Literal["image_url"], Field(..., description="Always `image_url`.")]
    """Always `image_url`."""

    model_config = ConfigDict(extra="ignore")

ModerationImageURLInput.model_rebuild()