# Code generated by schema2code at 2026-02-23 18:45:19. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ModifyCertificateRequest(BaseModel):
    name: Annotated[str, Field(..., description="The updated name for the certificate")]
    """The updated name for the certificate"""

    model_config = ConfigDict(extra="ignore")