# Code generated by schema2code at 2026-02-23 18:45:48. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class OtherChunkingStrategyResponseParam(BaseModel):
    """This is returned when the chunking strategy is unknown. Typically, this is because the file was indexed before the `chunking_strategy` concept was introduced in the API."""
    type: Annotated[Literal["other"], Field(..., description="Always `other`.")]
    """Always `other`."""

    model_config = ConfigDict(extra="ignore")