# Code generated by schema2code at 2026-02-23 18:45:32. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.openai.mcp_list_tools_tool import MCPListToolsTool
from models.openai.realtime_conversation_item import RealtimeConversationItem
from models.openai.realtime_conversation_item_function_call import (
    RealtimeConversationItemFunctionCall,
)
from models.openai.realtime_conversation_item_function_call_output import (
    RealtimeConversationItemFunctionCallOutput,
)
from models.openai.realtime_conversation_item_message_assistant import (
    RealtimeConversationItemMessageAssistant,
)
from models.openai.realtime_conversation_item_message_system import (
    RealtimeConversationItemMessageSystem,
)
from models.openai.realtime_conversation_item_message_user import (
    RealtimeConversationItemMessageUser,
)
from models.openai.realtime_mcp_approval_request import RealtimeMCPApprovalRequest
from models.openai.realtime_mcp_approval_response import RealtimeMCPApprovalResponse
from models.openai.realtime_mcp_list_tools import RealtimeMCPListTools
from models.openai.realtime_mcp_protocol_error import RealtimeMCPProtocolError
from models.openai.realtime_mcp_tool_call import RealtimeMCPToolCall
from models.openai.realtime_mcp_tool_execution_error import (
    RealtimeMCPToolExecutionError,
)
from models.openai.realtime_mcphttp_error import RealtimeMCPHTTPError
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class RealtimeServerEventConversationItemRetrieved(BaseModel):
    """Returned when a conversation item is retrieved with `conversation.item.retrieve`. This is provided as a way to fetch the server's representation of an item, for example to get access to the post-processed audio data after noise cancellation and VAD. It includes the full content of the Item, including audio data."""

    event_id: Annotated[
        str, Field(..., description="The unique ID of the server event.")
    ]
    """The unique ID of the server event."""
    item: Annotated[RealtimeConversationItem, Field(...)]
    type: Annotated[
        str,
        Field(
            ..., description="The event type, must be `conversation.item.retrieved`."
        ),
    ]
    """The event type, must be `conversation.item.retrieved`."""

    model_config = ConfigDict(extra="ignore")
