# Code generated by schema2code at 2026-02-23 18:45:32. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.openai.mcp_list_tools_tool import MCPListToolsTool
from models.openai.realtime_conversation_item_function_call import (
    RealtimeConversationItemFunctionCall,
)
from models.openai.realtime_conversation_item_function_call_output import (
    RealtimeConversationItemFunctionCallOutput,
)
from models.openai.realtime_conversation_item_message_assistant import (
    RealtimeConversationItemMessageAssistant,
)
from models.openai.realtime_conversation_item_message_system import (
    RealtimeConversationItemMessageSystem,
)
from models.openai.realtime_conversation_item_message_user import (
    RealtimeConversationItemMessageUser,
)
from models.openai.realtime_mcp_approval_request import RealtimeMCPApprovalRequest
from models.openai.realtime_mcp_approval_response import RealtimeMCPApprovalResponse
from models.openai.realtime_mcp_list_tools import RealtimeMCPListTools
from models.openai.realtime_mcp_protocol_error import RealtimeMCPProtocolError
from models.openai.realtime_mcp_tool_call import RealtimeMCPToolCall
from models.openai.realtime_mcp_tool_execution_error import (
    RealtimeMCPToolExecutionError,
)
from models.openai.realtime_mcphttp_error import RealtimeMCPHTTPError
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


RealtimeConversationItem = Union[
    RealtimeConversationItemMessageSystem,
    RealtimeConversationItemMessageUser,
    RealtimeConversationItemMessageAssistant,
    RealtimeConversationItemFunctionCall,
    RealtimeConversationItemFunctionCallOutput,
    RealtimeMCPApprovalResponse,
    RealtimeMCPListTools,
    RealtimeMCPToolCall,
    RealtimeMCPApprovalRequest,
]
