# Code generated by schema2code at 2026-02-23 18:45:24. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .audio_transcription import AudioTranscription
from .noise_reduction_type import NoiseReductionType
from .prompt import Prompt
from .realtime_function_tool import RealtimeFunctionTool
from .realtime_session import RealtimeSession
from .realtime_turn_detection import RealtimeTurnDetection
from .response_prompt_variables import ResponsePromptVariables
from .voice_ids_shared import VoiceIdsShared
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class InputAudioNoiseReduction(BaseModel):
    """Configuration for input audio noise reduction. This can be set to `null` to turn off.
Noise reduction filters audio added to the input audio buffer before it is sent to VAD and the model.
Filtering the audio can improve VAD and turn detection accuracy (reducing false positives) and model performance by improving perception of the input audio.
"""
    type: Annotated[Optional[NoiseReductionType], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")

class TracingConfiguration(BaseModel):
    """Granular configuration for tracing.
"""
    group_id: Annotated[Optional[str], Field(default=None, description="The group id to attach to this trace to enable filtering and grouping in the traces dashboard. ")] = None
    """The group id to attach to this trace to enable filtering and grouping in the traces dashboard. """
    metadata: Annotated[Optional[Dict[str, Any]], Field(default=None, description="The arbitrary metadata to attach to this trace to enable filtering in the traces dashboard. ")] = None
    """The arbitrary metadata to attach to this trace to enable filtering in the traces dashboard. """
    workflow_name: Annotated[Optional[str], Field(default=None, description="The name of the workflow to attach to this trace. This is used to name the trace in the traces dashboard. ")] = None
    """The name of the workflow to attach to this trace. This is used to name the trace in the traces dashboard. """

    model_config = ConfigDict(extra="ignore")

class RealtimeBetaServerEventSessionCreated(BaseModel):
    """Returned when a Session is created. Emitted automatically when a new
connection is established as the first server event. This event will contain
the default Session configuration.
"""
    event_id: Annotated[str, Field(..., description="The unique ID of the server event.")]
    """The unique ID of the server event."""
    session: Annotated[RealtimeSession, Field(...)]
    type: Annotated[str, Field(..., description="The event type, must be `session.created`.")]
    """The event type, must be `session.created`."""

    model_config = ConfigDict(extra="ignore")

RealtimeBetaServerEventSessionCreated.model_rebuild()