# Code generated by schema2code at 2026-02-23 18:45:32. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

# No relative imports - file only imports from pydantic



class RealtimeMCPProtocolError(BaseModel):
    code: Annotated[int, Field(...)]
    message: Annotated[str, Field(...)]
    type: Annotated[Literal["protocol_error"], Field(...)]

    model_config = ConfigDict(extra="ignore")