# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class RefusalContent(BaseModel):
    """A refusal from the model."""
    refusal: Annotated[str, Field(..., description="The refusal explanation from the model.")]
    """The refusal explanation from the model."""
    type: Annotated[Literal["refusal"], Field(default='refusal', description="The type of the refusal. Always `refusal`.")]
    """The type of the refusal. Always `refusal`."""

    model_config = ConfigDict(extra="ignore")