# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.openai.annotation import Annotation
from models.openai.container_file_citation_body import ContainerFileCitationBody
from models.openai.file_citation_body import FileCitationBody
from models.openai.file_path import FilePath
from models.openai.log_prob import LogProb
from models.openai.output_content import OutputContent
from models.openai.output_text_content import OutputTextContent
from models.openai.reasoning_text_content import ReasoningTextContent
from models.openai.refusal_content import RefusalContent
from models.openai.top_log_prob import TopLogProb
from models.openai.url_citation_body import UrlCitationBody
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class ResponseContentPartAddedEvent(BaseModel):
    """Emitted when a new content part is added."""

    content_index: Annotated[
        int, Field(..., description="The index of the content part that was added. ")
    ]
    """The index of the content part that was added. """
    item_id: Annotated[
        str,
        Field(
            ...,
            description="The ID of the output item that the content part was added to. ",
        ),
    ]
    """The ID of the output item that the content part was added to. """
    output_index: Annotated[
        int,
        Field(
            ...,
            description="The index of the output item that the content part was added to. ",
        ),
    ]
    """The index of the output item that the content part was added to. """
    part: Annotated[
        OutputContent, Field(..., description="The content part that was added. ")
    ]
    """The content part that was added. """
    sequence_number: Annotated[
        int, Field(..., description="The sequence number of this event.")
    ]
    """The sequence number of this event."""
    type: Annotated[
        Literal["response.content_part.added"],
        Field(
            ...,
            description="The type of the event. Always `response.content_part.added`. ",
        ),
    ]
    """The type of the event. Always `response.content_part.added`. """

    model_config = ConfigDict(extra="ignore")
