# Code generated by schema2code at 2026-02-23 18:45:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class InputTokensDetails(BaseModel):
    """A detailed breakdown of the input tokens."""
    cached_tokens: Annotated[int, Field(..., description="The number of tokens that were retrieved from the cache.  [More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching). ")]
    """The number of tokens that were retrieved from the cache.  [More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching). """

    model_config = ConfigDict(extra="ignore")

class OutputTokensDetails(BaseModel):
    """A detailed breakdown of the output tokens."""
    reasoning_tokens: Annotated[int, Field(..., description="The number of reasoning tokens.")]
    """The number of reasoning tokens."""

    model_config = ConfigDict(extra="ignore")

class ResponseUsage(BaseModel):
    """Represents token usage details including input tokens, output tokens,
a breakdown of output tokens, and the total tokens used.
"""
    input_tokens: Annotated[int, Field(..., description="The number of input tokens.")]
    """The number of input tokens."""
    input_tokens_details: Annotated[InputTokensDetails, Field(..., description="A detailed breakdown of the input tokens.")]
    """A detailed breakdown of the input tokens."""
    output_tokens: Annotated[int, Field(..., description="The number of output tokens.")]
    """The number of output tokens."""
    output_tokens_details: Annotated[OutputTokensDetails, Field(..., description="A detailed breakdown of the output tokens.")]
    """A detailed breakdown of the output tokens."""
    total_tokens: Annotated[int, Field(..., description="The total number of tokens used.")]
    """The total number of tokens used."""

    model_config = ConfigDict(extra="ignore")

ResponseUsage.model_rebuild()