# Code generated by schema2code at 2026-02-23 18:45:40. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class MessageCreation(BaseModel):
    message_id: Annotated[Optional[str], Field(default=None, description="The ID of the message that was created by this run step.")] = None
    """The ID of the message that was created by this run step."""

    model_config = ConfigDict(extra="ignore")

class RunStepDeltaStepDetailsMessageCreationObject(BaseModel):
    """Details of the message creation by the run step."""
    message_creation: Annotated[Optional[MessageCreation], Field(default=None)] = None
    type: Annotated[Literal["message_creation"], Field(..., description="Always `message_creation`.")]
    """Always `message_creation`."""

    model_config = ConfigDict(extra="ignore")

RunStepDeltaStepDetailsMessageCreationObject.model_rebuild()