# Code generated by schema2code at 2026-02-23 18:45:39. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Usage(BaseModel):
    """Token usage statistics for the request.
"""
    input_tokens: Annotated[int, Field(..., description="Number of input tokens in the prompt.")]
    """Number of input tokens in the prompt."""
    output_tokens: Annotated[int, Field(..., description="Number of output tokens generated.")]
    """Number of output tokens generated."""
    total_tokens: Annotated[int, Field(..., description="Total number of tokens used (input + output).")]
    """Total number of tokens used (input + output)."""

    model_config = ConfigDict(extra="ignore")

class SpeechAudioDoneEvent(BaseModel):
    """Emitted when the speech synthesis is complete and all audio has been streamed."""
    type: Annotated[Literal["speech.audio.done"], Field(..., description="The type of the event. Always `speech.audio.done`. ")]
    """The type of the event. Always `speech.audio.done`. """
    usage: Annotated[Usage, Field(..., description="Token usage statistics for the request. ")]
    """Token usage statistics for the request. """

    model_config = ConfigDict(extra="ignore")

SpeechAudioDoneEvent.model_rebuild()