# Code generated by schema2code at 2026-02-23 18:45:39. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .static_chunking_strategy import StaticChunkingStrategy
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class StaticChunkingStrategyRequestParam(BaseModel):
    """Customize your own chunking strategy by setting chunk size and chunk overlap."""
    static: Annotated[StaticChunkingStrategy, Field(...)]
    type: Annotated[Literal["static"], Field(..., description="Always `static`.")]
    """Always `static`."""

    model_config = ConfigDict(extra="ignore")