# Code generated by schema2code at 2026-02-23 18:45:48. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ToolChoiceFunction(BaseModel):
    """Use this option to force the model to call a specific function.
"""
    name: Annotated[str, Field(..., description="The name of the function to call.")]
    """The name of the function to call."""
    type: Annotated[Literal["function"], Field(..., description="For function calling, the type is always `function`.")]
    """For function calling, the type is always `function`."""

    model_config = ConfigDict(extra="ignore")