# Code generated by schema2code at 2026-02-23 18:45:47. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class UserMessageInputText(BaseModel):
    """Text block that a user contributed to the thread."""
    text: Annotated[str, Field(..., description="Plain-text content supplied by the user.")]
    """Plain-text content supplied by the user."""
    type: Annotated[Literal["input_text"], Field(default='input_text', description="Type discriminator that is always `input_text`.")]
    """Type discriminator that is always `input_text`."""

    model_config = ConfigDict(extra="ignore")