# Code generated by schema2code at 2026-02-23 18:45:52. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Data(BaseModel):
    """Event data payload.
"""
    id: Annotated[str, Field(..., description="The unique ID of the model response. ")]
    """The unique ID of the model response. """

    model_config = ConfigDict(extra="ignore")

class WebhookResponseIncomplete(BaseModel):
    """Sent when a background response has been interrupted.
"""
    created_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) of when the model response was interrupted. ")]
    """The Unix timestamp (in seconds) of when the model response was interrupted. """
    data: Annotated[Data, Field(..., description="Event data payload. ")]
    """Event data payload. """
    id: Annotated[str, Field(..., description="The unique ID of the event. ")]
    """The unique ID of the event. """
    object: Annotated[Optional[Literal["event"]], Field(default=None, description="The object of the event. Always `event`. ")] = None
    """The object of the event. Always `event`. """
    type: Annotated[Literal["response.incomplete"], Field(..., description="The type of the event. Always `response.incomplete`. ")]
    """The type of the event. Always `response.incomplete`. """

    model_config = ConfigDict(extra="ignore")

WebhookResponseIncomplete.model_rebuild()