# Code generated by schema2code at 2026-02-23 18:45:52. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class WorkflowTracingParam(BaseModel):
    """Controls diagnostic tracing during the session."""
    enabled: Annotated[Optional[bool], Field(default=None, description="Whether tracing is enabled during the session. Defaults to true.")] = None
    """Whether tracing is enabled during the session. Defaults to true."""

    model_config = ConfigDict(extra="ignore")