apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: llmmll
type: Opaque
stringData:
  POSTGRES_USER: "lsm"
  POSTGRES_PASSWORD: "7cb9c812e384e16c911a72f1066517d205e8641b78edb3b1b3c78d0c351b1885"
  POSTGRES_DB: "llmmll"