apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "llmmll"
spec:
  selector:
    app: psql
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  type: ClusterIP
  publishNotReadyAddresses: true