# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat
from .create_message_request import CreateMessageRequest


class BatchRequest(BaseModel):
    custom_id: Annotated[
        str,
        Field(
            ...,
            description="Developer-assigned identifier for this request (opaque, no PII).",
        ),
    ]
    """Developer-assigned identifier for this request (opaque, no PII)."""
    params: Annotated[CreateMessageRequest, Field(...)]

    model_config = ConfigDict(extra="ignore")


BatchRequest.model_rebuild()
