# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class BatchRequestCount(BaseModel):
    processing: Annotated[Optional[int], Field(default=None)] = None
    succeeded: Annotated[Optional[int], Field(default=None)] = None
    errored: Annotated[Optional[int], Field(default=None)] = None
    canceled: Annotated[Optional[int], Field(default=None)] = None
    expired: Annotated[Optional[int], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")