# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class BatchRequestCount(BaseModel):
    processing: Annotated[Optional[int], Field(default=None)] = None
    succeeded: Annotated[Optional[int], Field(default=None)] = None
    errored: Annotated[Optional[int], Field(default=None)] = None
    canceled: Annotated[Optional[int], Field(default=None)] = None
    expired: Annotated[Optional[int], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")

class BatchResponse(BaseModel):
    id: Annotated[str, Field(..., description="Batch identifier (`msgbatch_…`).")]
    """Batch identifier (`msgbatch_…`)."""
    type: Annotated[Literal["message_batch"], Field(...)]
    processing_status: Annotated[Literal["in_progress", "canceling", "ended"], Field(...)]
    request_counts: Annotated[BatchRequestCount, Field(...)]
    ended_at: Annotated[Optional[datetime], Field(default=None)] = None
    created_at: Annotated[datetime, Field(...)]
    expires_at: Annotated[datetime, Field(...)]
    cancel_initiated_at: Annotated[Optional[datetime], Field(default=None)] = None
    results_url: Annotated[Optional[str], Field(default=None, description="URL to download JSONL results when processing is complete.")] = None
    """URL to download JSONL results when processing is complete."""

    model_config = ConfigDict(extra="ignore")

BatchResponse.model_rebuild()