# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class CacheControl(BaseModel):
    type: Annotated[Literal["ephemeral"], Field(...)]
    ttl: Annotated[Optional[str], Field(default=None, description="Time-to-live for the cache entry. Defaults to `5m`.")] = None
    """Time-to-live for the cache entry. Defaults to `5m`."""

    model_config = ConfigDict(extra="ignore")