# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat
from .input_schema import InputSchema
from .cache_control import CacheControl


class ClientTool(BaseModel):
    """A client-side tool definition."""

    type: Annotated[
        Optional[Literal["custom"]],
        Field(default=None, description="Omit or set to `custom` for client tools."),
    ] = None
    """Omit or set to `custom` for client tools."""
    name: Annotated[
        str,
        Field(..., description="Tool name (used by the model when calling the tool)."),
    ]
    """Tool name (used by the model when calling the tool)."""
    description: Annotated[
        Optional[str],
        Field(default=None, description="Detailed description of what the tool does."),
    ] = None
    """Detailed description of what the tool does."""
    input_schema: Annotated[
        InputSchema, Field(..., description="JSON Schema for the tool's input.")
    ]
    """JSON Schema for the tool's input."""
    cache_control: Annotated[Optional[CacheControl], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")


ClientTool.model_rebuild()
