# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from .input_message import InputMessage
from .system_prompt import SystemPrompt
from .tool import Tool
from .thinking_config import ThinkingConfig


class CountTokensRequest(BaseModel):
    model: Annotated[str, Field(...)]
    messages: Annotated[List[InputMessage], Field(...)]
    system: Annotated[Optional[SystemPrompt], Field(default=None)] = None
    tools: Annotated[Optional[List[Tool]], Field(default=None)] = None
    thinking: Annotated[Optional[ThinkingConfig], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")


CountTokensRequest.model_rebuild()
