# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat
from .metadata import Metadata


class CreateCompletionRequest(BaseModel):
    model: Annotated[str, Field(...)]
    prompt: Annotated[
        str,
        Field(
            ...,
            description="Alternating `\n\nHuman:` / `\n\nAssistant:` formatted prompt. ",
        ),
    ]
    """Alternating `\n\nHuman:` / `\n\nAssistant:` formatted prompt. """
    max_tokens_to_sample: Annotated[int, Field(..., ge=1)]
    stop_sequences: Annotated[Optional[List[str]], Field(default=None)] = None
    temperature: Annotated[Optional[float], Field(default=1.0, ge=0.0, le=1.0)] = 1.0
    top_p: Annotated[Optional[float], Field(default=None)] = None
    top_k: Annotated[Optional[int], Field(default=None)] = None
    stream: Annotated[Optional[bool], Field(default=False)] = False
    metadata: Annotated[Optional[Metadata], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")


CreateCompletionRequest.model_rebuild()
