# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from .text_content_block import TextContentBlock


class DocumentSource(BaseModel):
    type: Annotated[Literal["base64", "url", "file", "text", "content"], Field(...)]
    media_type: Annotated[
        Optional[Literal["application/pdf", "text/plain"]], Field(default=None)
    ] = None
    data: Annotated[Optional[str], Field(default=None)] = None
    url: Annotated[Optional[AnyUrl], Field(default=None)] = None
    file_id: Annotated[Optional[str], Field(default=None)] = None
    text: Annotated[
        Optional[str],
        Field(default=None, description="Plain text content when type is `text`."),
    ] = None
    """Plain text content when type is `text`."""
    content: Annotated[
        Optional[List[TextContentBlock]],
        Field(
            default=None, description="Custom content blocks when type is `content`."
        ),
    ] = None
    """Custom content blocks when type is `content`."""

    model_config = ConfigDict(extra="ignore")


DocumentSource.model_rebuild()
