# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class FileMetadata(BaseModel):
    id: Annotated[str, Field(..., description="File identifier (`file_…`).")]
    """File identifier (`file_…`)."""
    type: Annotated[Literal["file"], Field(...)]
    filename: Annotated[str, Field(...)]
    size: Annotated[int, Field(..., description="File size in bytes.")]
    """File size in bytes."""
    created_at: Annotated[datetime, Field(...)]
    purpose: Annotated[Optional[str], Field(default=None, description="Intended use of the file.")] = None
    """Intended use of the file."""

    model_config = ConfigDict(extra="ignore")