# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from models.anthropic.cache_control import CacheControl
from models.anthropic.image_source import ImageSource


class ImageContentBlock(BaseModel):
    type: Annotated[Literal["image"], Field(...)]
    source: Annotated[ImageSource, Field(...)]
    cache_control: Annotated[Optional[CacheControl], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")


ImageContentBlock.model_rebuild()
