# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ImageSource(BaseModel):
    type: Annotated[Literal["base64", "url", "file"], Field(...)]
    media_type: Annotated[Optional[Literal["image/jpeg", "image/png", "image/gif", "image/webp"]], Field(default=None, description="Required when type is `base64`.")] = None
    """Required when type is `base64`."""
    data: Annotated[Optional[str], Field(default=None, description="Base64-encoded image data. Required when type is `base64`.")] = None
    """Base64-encoded image data. Required when type is `base64`."""
    url: Annotated[Optional[AnyUrl], Field(default=None, description="URL of the image. Required when type is `url`.")] = None
    """URL of the image. Required when type is `url`."""
    file_id: Annotated[Optional[str], Field(default=None, description="File ID from the Files API. Required when type is `file`.")] = None
    """File ID from the Files API. Required when type is `file`."""

    model_config = ConfigDict(extra="ignore")