# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from .document_content_block import DocumentContentBlock
from .image_content_block import ImageContentBlock
from .text_content_block import TextContentBlock
from .tool_result_content_block import ToolResultContentBlock
from .tool_use_content_block import ToolUseContentBlock

InputContentBlock = Union[
    TextContentBlock,
    ImageContentBlock,
    DocumentContentBlock,
    ToolUseContentBlock,
    ToolResultContentBlock,
]
