# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from .output_content_block import OutputContentBlock
from .usage import Usage


class MessageResponse(BaseModel):
    id: Annotated[str, Field(..., description="Unique message identifier (`msg_…`).")]
    """Unique message identifier (`msg_…`)."""
    type: Annotated[Literal["message"], Field(...)]
    role: Annotated[Literal["assistant"], Field(...)]
    content: Annotated[List[OutputContentBlock], Field(...)]
    model: Annotated[str, Field(...)]
    stop_reason: Annotated[
        Literal["end_turn", "max_tokens", "stop_sequence", "tool_use", "pause_turn"],
        Field(...),
    ]
    stop_sequence: Annotated[
        Optional[str],
        Field(
            default=None,
            description="Which stop sequence triggered the stop (if `stop_reason` is `stop_sequence`).",
        ),
    ] = None
    """Which stop sequence triggered the stop (if `stop_reason` is `stop_sequence`)."""
    usage: Annotated[Usage, Field(...)]

    model_config = ConfigDict(extra="ignore")


MessageResponse.model_rebuild()
