# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from models.anthropic.model import Model


class ModelListResponse(BaseModel):
    data: Annotated[List[Model], Field(...)]
    first_id: Annotated[Optional[str], Field(default=None)] = None
    last_id: Annotated[Optional[str], Field(default=None)] = None
    has_more: Annotated[bool, Field(...)]

    model_config = ConfigDict(extra="ignore")


ModelListResponse.model_rebuild()
