# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ServerTool(BaseModel):
    """An Anthropic-managed server-side tool."""
    type: Annotated[str, Field(..., description="Versioned tool type, e.g. `web_search_20250305`, `text_editor_20250124`, `bash_20250124`, `computer_20250124`.")]
    """Versioned tool type, e.g. `web_search_20250305`, `text_editor_20250124`, `bash_20250124`, `computer_20250124`."""
    name: Annotated[Optional[str], Field(default=None, description="Optional override name for the tool.")] = None
    """Optional override name for the tool."""

    model_config = ConfigDict(extra="ignore")