# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ToolUseContentBlock(BaseModel):
    """A tool invocation block in an assistant message."""
    type: Annotated[Literal["tool_use"], Field(...)]
    id: Annotated[str, Field(..., description="Unique identifier for this tool use.")]
    """Unique identifier for this tool use."""
    name: Annotated[str, Field(...)]
    input: Annotated[Dict[str, Any], Field(..., description="Tool input as a JSON object.")]
    """Tool input as a JSON object."""

    model_config = ConfigDict(extra="ignore")