# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ServerToolUse(BaseModel):
    web_search_requests: Annotated[Optional[int], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")

class Usage(BaseModel):
    input_tokens: Annotated[Optional[int], Field(default=None)] = None
    output_tokens: Annotated[Optional[int], Field(default=None)] = None
    cache_creation_input_tokens: Annotated[Optional[int], Field(default=None)] = None
    cache_read_input_tokens: Annotated[Optional[int], Field(default=None)] = None
    server_tool_use: Annotated[Optional[ServerToolUse], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")

Usage.model_rebuild()