# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.complexity_level import ComplexityLevel
from models.computational_requirement import ComputationalRequirement
from models.model_profile_type import ModelProfileType
from models.required_capability import RequiredCapability
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class CapabilityProfileMapping(BaseModel):
    """Mapping from required capabilities to appropriate model profile types"""

    capability: Annotated[
        RequiredCapability, Field(..., description="The required capability")
    ]
    """The required capability"""
    compatible_profiles: Annotated[
        List[ModelProfileType],
        Field(
            ...,
            description="List of model profile types that can fulfill this capability",
        ),
    ]
    """List of model profile types that can fulfill this capability"""
    preferred_profile: Annotated[
        ModelProfileType,
        Field(..., description="Preferred model profile type for this capability"),
    ]
    """Preferred model profile type for this capability"""
    minimum_complexity_level: Annotated[
        Optional[ComplexityLevel],
        Field(
            default=None,
            description="Minimum complexity level where this capability mapping applies",
        ),
    ] = None
    """Minimum complexity level where this capability mapping applies"""
    computational_requirements: Annotated[
        Optional[List[ComputationalRequirement]],
        Field(
            default=None,
            description="Computational requirements imposed by this capability",
        ),
    ] = None
    """Computational requirements imposed by this capability"""

    model_config = ConfigDict(extra="ignore")
