# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, constr



class ComplexityEstimate(str, Enum):
    """General complexity estimation for tasks and operations"""
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'