# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.complexity_level import ComplexityLevel
from models.computational_requirement import ComputationalRequirement
from models.conversation import Conversation
from models.document import Document
from models.image_metadata import ImageMetadata
from models.intent import Intent
from models.intent_analysis import IntentAnalysis
from models.message import Message
from models.message_content import MessageContent
from models.message_content_type import MessageContentType
from models.message_role import MessageRole
from models.required_capability import RequiredCapability
from models.resource_usage import ResourceUsage
from models.response_format import ResponseFormat
from models.technical_domain import TechnicalDomain
from models.thought import Thought
from models.tool_call import ToolCall
from models.workflow_type import WorkflowType
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class ConversationCtx(BaseModel):
    """Manages context for a conversation, including messages, summaries, and retrieved memories. Provides methods for adding messages, summarizing conversations, and retrieving relevant context."""

    messages: Annotated[
        List[Message], Field(..., description="List of messages in the conversation")
    ]
    """List of messages in the conversation"""
    notes: Annotated[
        List[str], Field(..., description="List of notes related to the conversation")
    ]
    """List of notes related to the conversation"""
    images: Annotated[
        List[ImageMetadata],
        Field(..., description="List of images associated with the conversation"),
    ]
    """List of images associated with the conversation"""
    conversation: Annotated[
        Conversation, Field(..., description="The conversation object")
    ]
    """The conversation object"""
    current_user_message: Annotated[
        Optional[Message],
        Field(default=None, description="The current message from the user"),
    ] = None
    """The current message from the user"""
    intent: Annotated[
        Optional[Intent],
        Field(default=None, description="The intent detected from the user's message"),
    ] = None
    """The intent detected from the user's message"""

    model_config = ConfigDict(extra="ignore")
