# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class CrashPrevention(BaseModel):
    """Settings to prevent container crashes during optimization"""
    enable_preallocation_test: Annotated[bool, Field(default=True, description="Test memory allocation before full initialization")]
    """Test memory allocation before full initialization"""
    memory_buffer_mb: Annotated[int, Field(default=1024, description="Memory buffer to reserve (MB) to prevent system OOM", ge=512, le=8192)]
    """Memory buffer to reserve (MB) to prevent system OOM"""
    timeout_seconds: Annotated[int, Field(default=120, description="Maximum time to wait for initialization before considering it failed", ge=30, le=300)]
    """Maximum time to wait for initialization before considering it failed"""
    enable_graceful_degradation: Annotated[bool, Field(default=True, description="Fall back to smaller parameters on failure")]
    """Fall back to smaller parameters on failure"""

    model_config = ConfigDict(extra="ignore")