# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Document(BaseModel):
    """A document/file attachment with metadata and content"""
    id: Annotated[Optional[int], Field(default=None, description="Unique identifier for the file attachment")] = None
    """Unique identifier for the file attachment"""
    message_id: Annotated[int, Field(..., description="ID of the message this attachment belongs to")]
    """ID of the message this attachment belongs to"""
    user_id: Annotated[str, Field(..., description="ID of the user who uploaded this attachment")]
    """ID of the user who uploaded this attachment"""
    filename: Annotated[str, Field(..., description="Original filename of the attachment")]
    """Original filename of the attachment"""
    content_type: Annotated[str, Field(..., description="MIME type of the file")]
    """MIME type of the file"""
    file_size: Annotated[int, Field(..., description="Size of the file in bytes")]
    """Size of the file in bytes"""
    content: Annotated[str, Field(..., description="File content (base64 encoded for binary files, plain text for text files)")]
    """File content (base64 encoded for binary files, plain text for text files)"""
    text_content: Annotated[Optional[str], Field(default=None, description="Extracted text content for searchability (null for images)")] = None
    """Extracted text content for searchability (null for images)"""
    created_at: Annotated[datetime, Field(..., description="Timestamp when the attachment was created")]
    """Timestamp when the attachment was created"""
    updated_at: Annotated[Optional[datetime], Field(default=None, description="Timestamp when the attachment was last updated")] = None
    """Timestamp when the attachment was last updated"""

    model_config = ConfigDict(extra="ignore")