# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class DynamicTool(BaseModel):
    """Schema for DynamicTool object that implements LangChain BaseTool interface"""
    id: Annotated[Optional[int], Field(default=None, description="The unique identifier for the tool")] = None
    """The unique identifier for the tool"""
    user_id: Annotated[str, Field(..., description="The unique identifier for the user")]
    """The unique identifier for the user"""
    embedding: Annotated[Optional[List[float]], Field(default=None, description="The tool's embedding vector")] = None
    """The tool's embedding vector"""
    code: Annotated[str, Field(..., description="The tool's implementation code")]
    """The tool's implementation code"""
    function_name: Annotated[str, Field(..., description="The name of the function to be called")]
    """The name of the function to be called"""
    created_at: Annotated[Optional[datetime], Field(default=None, description="The timestamp when the tool was created")] = None
    """The timestamp when the tool was created"""
    updated_at: Annotated[Optional[datetime], Field(default=None, description="The timestamp when the tool was last updated")] = None
    """The timestamp when the tool was last updated"""
    name: Annotated[str, Field(..., description="The unique name of the tool that clearly communicates its purpose")]
    """The unique name of the tool that clearly communicates its purpose"""
    description: Annotated[str, Field(..., description="Used to tell the model how/when/why to use the tool. You can provide few-shot examples as a part of the description")]
    """Used to tell the model how/when/why to use the tool. You can provide few-shot examples as a part of the description"""
    args_schema: Annotated[Optional[Union[Any, Dict[str, Any], str]], Field(default=None, description="Pydantic model class to validate and parse the tool's input arguments")] = None
    """Pydantic model class to validate and parse the tool's input arguments"""
    return_direct: Annotated[Optional[bool], Field(default=False, description="Whether to return the tool's output directly. Setting this to True means that after the tool is called, the AgentExecutor will stop looping")] = False
    """Whether to return the tool's output directly. Setting this to True means that after the tool is called, the AgentExecutor will stop looping"""
    tags: Annotated[Optional[List[str]], Field(default_factory=lambda: [], description="Optional list of tags associated with the tool. These tags will be associated with each call to this tool and passed as arguments to the handlers defined in callbacks")]
    """Optional list of tags associated with the tool. These tags will be associated with each call to this tool and passed as arguments to the handlers defined in callbacks"""
    metadata: Annotated[Optional[Dict[str, Any]], Field(default_factory=lambda: {}, description="Optional metadata associated with the tool. This metadata will be associated with each call to this tool and passed as arguments to the handlers defined in callbacks")]
    """Optional metadata associated with the tool. This metadata will be associated with each call to this tool and passed as arguments to the handlers defined in callbacks"""
    handle_tool_error: Annotated[Optional[Union[bool, str, Any]], Field(default=False, description="Handle the content of the ToolException thrown. Can be a boolean, string, or callable function")] = False
    """Handle the content of the ToolException thrown. Can be a boolean, string, or callable function"""
    handle_validation_error: Annotated[Optional[Union[bool, str, Any]], Field(default=False, description="Handle the content of the ValidationError thrown. Can be a boolean, string, or callable function")] = False
    """Handle the content of the ValidationError thrown. Can be a boolean, string, or callable function"""
    response_format: Annotated[Optional[Literal["content", "content_and_artifact"]], Field(default='content', description="The tool response format. If 'content' then the output is interpreted as ToolMessage contents. If 'content_and_artifact' then output is expected to be a two-tuple of (content, artifact)")] = 'content'
    """The tool response format. If 'content' then the output is interpreted as ToolMessage contents. If 'content_and_artifact' then output is expected to be a two-tuple of (content, artifact)"""
    parameters: Annotated[Optional[Dict[str, Any]], Field(default=None, description="Legacy parameters field - use args_schema for new implementations")] = None
    """Legacy parameters field - use args_schema for new implementations"""

    model_config = ConfigDict(extra="ignore")