# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.complexity_level import ComplexityLevel
from models.computational_requirement import ComputationalRequirement
from models.required_capability import RequiredCapability
from models.response_format import ResponseFormat
from models.technical_domain import TechnicalDomain
from models.workflow_type import WorkflowType
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class IntentAnalysis(BaseModel):
    """Detailed analysis of user intent for smart tool generation"""

    id: Annotated[
        Optional[int],
        Field(default=None, description="Unique identifier for the analysis record"),
    ] = None
    """Unique identifier for the analysis record"""
    message_id: Annotated[
        Optional[int],
        Field(
            default=None,
            description="ID of the associated message this analysis belongs to",
        ),
    ] = None
    """ID of the associated message this analysis belongs to"""
    task: Annotated[
        Optional[str],
        Field(
            default=None,
            description="The specific task inferred from the user message for this analysis",
        ),
    ] = None
    """The specific task inferred from the user message for this analysis"""
    workflow_type: Annotated[
        WorkflowType,
        Field(
            ..., description="Primary intent category identified from the user message"
        ),
    ]
    """Primary intent category identified from the user message"""
    complexity_level: Annotated[
        ComplexityLevel,
        Field(..., description="Assessed complexity level of the request"),
    ]
    """Assessed complexity level of the request"""
    required_capabilities: Annotated[
        List[RequiredCapability],
        Field(..., description="Set of capabilities required to fulfill the request"),
    ]
    """Set of capabilities required to fulfill the request"""
    domain_specificity: Annotated[
        float,
        Field(
            ...,
            description="Domain specificity score (0-1, higher = more domain-specific)",
            ge=0.0,
            le=1.0,
        ),
    ]
    """Domain specificity score (0-1, higher = more domain-specific)"""
    reusability_potential: Annotated[
        float,
        Field(
            ...,
            description="Reusability potential score (0-1, higher = more reusable)",
            ge=0.0,
            le=1.0,
        ),
    ]
    """Reusability potential score (0-1, higher = more reusable)"""
    confidence: Annotated[
        float,
        Field(..., description="Confidence in the analysis (0-1)", ge=0.0, le=1.0),
    ]
    """Confidence in the analysis (0-1)"""
    response_format: Annotated[
        Optional[ResponseFormat],
        Field(default=None, description="Suggested response format for the user"),
    ] = None
    """Suggested response format for the user"""
    technical_domain: Annotated[
        Optional[TechnicalDomain],
        Field(default=None, description="Identified technical domain if applicable"),
    ] = None
    """Identified technical domain if applicable"""
    requires_tools: Annotated[
        bool,
        Field(
            default=False,
            description="Whether this intent specifically requires tool execution",
        ),
    ]
    """Whether this intent specifically requires tool execution"""
    requires_custom_tools: Annotated[
        bool,
        Field(
            default=False,
            description="Whether this intent requires custom/dynamic tool generation",
        ),
    ]
    """Whether this intent requires custom/dynamic tool generation"""
    tool_complexity_score: Annotated[
        float,
        Field(
            ...,
            description="Tool complexity score (0-1, higher = more complex tools needed)",
            ge=0.0,
            le=1.0,
        ),
    ]
    """Tool complexity score (0-1, higher = more complex tools needed)"""
    computational_requirements: Annotated[
        ComputationalRequirement,
        Field(..., description="Computational requirements assessment for the request"),
    ]
    """Computational requirements assessment for the request"""
    created_at: Annotated[
        Optional[datetime],
        Field(default=None, description="Timestamp when the analysis was created"),
    ] = None
    """Timestamp when the analysis was created"""

    model_config = ConfigDict(extra="ignore")
