# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.complexity_level import ComplexityLevel
from models.computational_requirement import ComputationalRequirement
from models.document import Document
from models.intent_analysis import IntentAnalysis
from models.message import Message
from models.message_content import MessageContent
from models.message_content_type import MessageContentType
from models.message_role import MessageRole
from models.required_capability import RequiredCapability
from models.resource_usage import ResourceUsage
from models.response_format import ResponseFormat
from models.technical_domain import TechnicalDomain
from models.thought import Thought
from models.tool_call import ToolCall
from models.workflow_type import WorkflowType
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class LangGraphState(BaseModel):
    """Strongly typed state for LangGraph workflows."""

    messages: Annotated[List[Message], Field(..., description="Sequence of messages")]
    """Sequence of messages"""
    user_input: Annotated[str, Field(..., description="Latest user input")]
    """Latest user input"""
    error_count: Annotated[
        int,
        Field(
            default=0,
            description="Number of errors encountered during workflow execution",
        ),
    ]
    """Number of errors encountered during workflow execution"""
    max_iterations: Annotated[
        int,
        Field(
            default=10,
            description="Maximum number of iterations allowed in the workflow",
        ),
    ]
    """Maximum number of iterations allowed in the workflow"""
    current_iteration: Annotated[
        int,
        Field(
            default=0, description="Current iteration count in the workflow execution"
        ),
    ]
    """Current iteration count in the workflow execution"""
    tools_used: Annotated[
        List[str],
        Field(
            default_factory=lambda: [],
            description="List of tools or functions that have been used in the workflow",
        ),
    ]
    """List of tools or functions that have been used in the workflow"""
    intermediate_results: Annotated[
        Dict[str, Any],
        Field(
            default_factory=lambda: {},
            description="Storage for intermediate computation results during workflow execution",
        ),
    ]
    """Storage for intermediate computation results during workflow execution"""

    model_config = ConfigDict(extra="ignore")
