# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class LearnedLimits(BaseModel):
    """Learned maximum limits from successful configurations"""
    max_context: Annotated[int, Field(..., description="Maximum context window size learned", ge=1)]
    """Maximum context window size learned"""
    max_batch: Annotated[int, Field(..., description="Maximum batch size learned", ge=1)]
    """Maximum batch size learned"""
    max_gpu_layers: Annotated[int, Field(..., description="Maximum GPU layers learned", ge=-1)]
    """Maximum GPU layers learned"""
    context_95th_percentile: Annotated[int, Field(..., description="95th percentile of successful context sizes", ge=1)]
    """95th percentile of successful context sizes"""
    batch_95th_percentile: Annotated[int, Field(..., description="95th percentile of successful batch sizes", ge=1)]
    """95th percentile of successful batch sizes"""
    gpu_layers_95th_percentile: Annotated[int, Field(..., description="95th percentile of successful GPU layer counts", ge=-1)]
    """95th percentile of successful GPU layer counts"""

    model_config = ConfigDict(extra="ignore")