# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.message_content_type import MessageContentType
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class MessageContent(BaseModel):
    """Content of a message in a chat conversation"""

    id: Annotated[
        Optional[int],
        Field(default=None, description="Unique identifier for the message content"),
    ] = None
    """Unique identifier for the message content"""
    message_id: Annotated[
        Optional[int],
        Field(
            default=None, description="Foreign key reference to the associated message"
        ),
    ] = None
    """Foreign key reference to the associated message"""
    type: Annotated[
        MessageContentType,
        Field(
            ...,
            description="Type of the message content (e.g., text, image, tool call)",
        ),
    ]
    """Type of the message content (e.g., text, image, tool call)"""
    text: Annotated[
        Optional[str],
        Field(default=None, description="Text content of the message, if applicable"),
    ] = None
    """Text content of the message, if applicable"""
    url: Annotated[
        Optional[str],
        Field(default=None, description="URL of the image or resource, if applicable"),
    ] = None
    """URL of the image or resource, if applicable"""
    format: Annotated[
        Optional[str],
        Field(
            default=None,
            description="Format of the content (e.g., 'mp3' for audio, 'mp4' for video)",
        ),
    ] = None
    """Format of the content (e.g., 'mp3' for audio, 'mp4' for video)"""
    name: Annotated[
        Optional[str],
        Field(default=None, description="Name of the file/image/etc., if applicable"),
    ] = None
    """Name of the file/image/etc., if applicable"""
    created_at: Annotated[
        Optional[datetime],
        Field(
            default=None, description="Timestamp when the message content was created"
        ),
    ] = None
    """Timestamp when the message content was created"""

    model_config = ConfigDict(extra="ignore")
