# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.complexity_level import ComplexityLevel
from models.computational_requirement import ComputationalRequirement
from models.document import Document
from models.intent_analysis import IntentAnalysis
from models.message_content import MessageContent
from models.message_content_type import MessageContentType
from models.message_role import MessageRole
from models.required_capability import RequiredCapability
from models.resource_usage import ResourceUsage
from models.response_format import ResponseFormat
from models.technical_domain import TechnicalDomain
from models.thought import Thought
from models.tool_call import ToolCall
from models.workflow_type import WorkflowType
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class Message(BaseModel):
    """Message represents a single exchange in the conversation"""

    role: Annotated[
        MessageRole,
        Field(..., description="Role of the message sender (e.g., user, assistant)"),
    ]
    """Role of the message sender (e.g., user, assistant)"""
    content: Annotated[
        List[MessageContent], Field(..., description="Content of the message")
    ]
    """Content of the message"""
    id: Annotated[
        Optional[int],
        Field(default=None, description="Unique identifier for the message"),
    ] = None
    """Unique identifier for the message"""
    created_at: Annotated[
        Optional[datetime],
        Field(default=None, description="Timestamp of when the message was created"),
    ] = None
    """Timestamp of when the message was created"""
    conversation_id: Annotated[
        Optional[int],
        Field(default=None, description="Unique identifier for the conversation"),
    ] = None
    """Unique identifier for the conversation"""
    thoughts: Annotated[
        Optional[List[Thought]],
        Field(
            default=None,
            description="Array of thoughts or reasoning processes from the assistant",
        ),
    ] = None
    """Array of thoughts or reasoning processes from the assistant"""
    tool_calls: Annotated[
        Optional[List[ToolCall]],
        Field(
            default=None, description="Array of tool calls associated with the message"
        ),
    ] = None
    """Array of tool calls associated with the message"""
    analyses: Annotated[
        Optional[List[IntentAnalysis]],
        Field(
            default=None,
            description="Array of intent analyses associated with the message",
        ),
    ] = None
    """Array of intent analyses associated with the message"""
    documents: Annotated[
        Optional[List[Document]],
        Field(default=None, description="Array of documents attached to the message"),
    ] = None
    """Array of documents attached to the message"""
    structured_output: Annotated[
        Optional[Dict[str, Any]],
        Field(default=None, description="Structured output data from the message"),
    ] = None
    """Structured output data from the message"""

    model_config = ConfigDict(extra="ignore")
