# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class MLModelPerformance(BaseModel):
    """ML model performance metrics for OOM recovery predictions"""
    n_ctx_mse: Annotated[float, Field(..., description="Mean squared error for context window predictions", ge=0)]
    """Mean squared error for context window predictions"""
    n_batch_mse: Annotated[float, Field(..., description="Mean squared error for batch size predictions", ge=0)]
    """Mean squared error for batch size predictions"""
    n_ubatch_mse: Annotated[float, Field(..., description="Mean squared error for micro-batch size predictions", ge=0)]
    """Mean squared error for micro-batch size predictions"""
    n_gpu_layers_mse: Annotated[float, Field(..., description="Mean squared error for GPU layer predictions", ge=0)]
    """Mean squared error for GPU layer predictions"""
    total_configurations: Annotated[int, Field(..., description="Total number of configurations used for training", ge=0)]
    """Total number of configurations used for training"""
    models_trained: Annotated[bool, Field(..., description="Whether ML models have been successfully trained")]
    """Whether ML models have been successfully trained"""

    model_config = ConfigDict(extra="ignore")