# Code generated by schema2code at 2026-03-07 19:34:29. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ModelConfigurationData(BaseModel):
    """Configuration parameters and results for model initialization attempts"""
    n_ctx: Annotated[int, Field(..., description="Context window size used", ge=1)]
    """Context window size used"""
    n_batch: Annotated[int, Field(..., description="Batch size used", ge=1)]
    """Batch size used"""
    n_ubatch: Annotated[int, Field(..., description="Micro-batch size used", ge=1)]
    """Micro-batch size used"""
    n_gpu_layers: Annotated[int, Field(..., description="Number of GPU layers used", ge=-1)]
    """Number of GPU layers used"""
    model_size_mb: Annotated[float, Field(..., description="Model size in megabytes", ge=0)]
    """Model size in megabytes"""
    available_gpu_memory_mb: Annotated[float, Field(..., description="Available GPU memory at initialization in MB", ge=0)]
    """Available GPU memory at initialization in MB"""
    total_gpu_memory_mb: Annotated[float, Field(..., description="Total GPU memory in MB", ge=0)]
    """Total GPU memory in MB"""
    success: Annotated[bool, Field(..., description="Whether initialization was successful")]
    """Whether initialization was successful"""
    gpu_memory_used_mb: Annotated[Optional[float], Field(default=None, description="GPU memory used after initialization in MB", ge=0)] = None
    """GPU memory used after initialization in MB"""
    initialization_time_ms: Annotated[Optional[float], Field(default=None, description="Time taken for initialization in milliseconds", ge=0)] = None
    """Time taken for initialization in milliseconds"""

    model_config = ConfigDict(extra="ignore", protected_namespaces=())