# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class OOMRecoveryAttemptData(BaseModel):
    """Single OOM recovery attempt configuration and result"""
    attempt: Annotated[int, Field(..., description="Attempt number in the recovery sequence", ge=1)]
    """Attempt number in the recovery sequence"""
    strategy: Annotated[Literal["clear_memory", "reduce_batch", "move_to_cpu", "reduce_context"], Field(..., description="Recovery strategy used in this attempt")]
    """Recovery strategy used in this attempt"""
    n_ctx: Annotated[int, Field(..., description="Context window size used in this attempt", ge=1)]
    """Context window size used in this attempt"""
    n_batch: Annotated[int, Field(..., description="Batch size used in this attempt", ge=1)]
    """Batch size used in this attempt"""
    n_ubatch: Annotated[int, Field(..., description="Micro-batch size used in this attempt", ge=1)]
    """Micro-batch size used in this attempt"""
    n_gpu_layers: Annotated[int, Field(..., description="Number of GPU layers used in this attempt", ge=-1)]
    """Number of GPU layers used in this attempt"""
    success: Annotated[bool, Field(..., description="Whether this attempt was successful")]
    """Whether this attempt was successful"""
    error_message: Annotated[str, Field(..., description="Error message if the attempt failed")]
    """Error message if the attempt failed"""

    model_config = ConfigDict(extra="ignore")