# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class OptimalParameters(BaseModel):
    """Optimal parameters predicted by ML models for LLM initialization"""
    n_ctx: Annotated[int, Field(..., description="Context window size", ge=1)]
    """Context window size"""
    n_batch: Annotated[int, Field(..., description="Batch size for processing", ge=1)]
    """Batch size for processing"""
    n_ubatch: Annotated[int, Field(..., description="Micro-batch size", ge=1)]
    """Micro-batch size"""
    n_gpu_layers: Annotated[int, Field(..., description="Number of model layers to place on GPU (-1 means all layers)", ge=-1)]
    """Number of model layers to place on GPU (-1 means all layers)"""

    model_config = ConfigDict(extra="ignore")