# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .crash_prevention import CrashPrevention
from .parameter_tuning_strategy import ParameterTuningStrategy
from .performance_parameter import PerformanceParameter
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ParameterOptimizationConfig(BaseModel):
    """Configuration for optimizing LLM initialization parameters to find maximum values"""
    enabled: Annotated[bool, Field(default=False, description="Enable parameter optimization to find maximum viable values")]
    """Enable parameter optimization to find maximum viable values"""
    parameters: Annotated[List[PerformanceParameter], Field(..., description="List of performance parameters to optimize")]
    """List of performance parameters to optimize"""
    crash_prevention: Annotated[CrashPrevention, Field(..., description="Settings to prevent container crashes during optimization")]
    """Settings to prevent container crashes during optimization"""

    model_config = ConfigDict(extra="ignore")