# Code generated by schema2code at 2025-11-06 18:22:56. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .parameter_tuning_strategy import ParameterTuningStrategy
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class PerformanceParameters(BaseModel):
    """Performance parameters for model initialization"""
    parameter_name: Annotated[Literal["n_ctx", "n_batch", "n_ubatch", "n_gpu_layers"], Field(..., description="Name of the performance parameter")]
    """Name of the performance parameter"""
    priority: Annotated[int, Field(..., description="Priority of the parameter for optimization (lower number = higher priority)", ge=1)]
    """Priority of the parameter for optimization (lower number = higher priority)"""
    tuning_strategy: Annotated[ParameterTuningStrategy, Field(..., description="Strategy for tuning this parameter")]
    """Strategy for tuning this parameter"""
    max_search_attempts: Annotated[int, Field(..., description="Maximum number of search attempts for this parameter", ge=1, le=20)]
    """Maximum number of search attempts for this parameter"""
    floor: Annotated[Optional[int], Field(default=None, description="Minimum value for the parameter during optimization", ge=1)] = None
    """Minimum value for the parameter during optimization"""

    model_config = ConfigDict(extra="ignore")