# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .parameter_tuning_strategy import ParameterTuningStrategy
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class PerformanceParameter(BaseModel):
    """Performance parameters for model initialization"""
    parameter_name: Annotated[Literal["n_ctx", "n_batch", "n_ubatch", "n_gpu_layers"], Field(..., description="Name of the performance parameter")]
    """Name of the performance parameter"""
    priority: Annotated[int, Field(..., description="Priority of the parameter for optimization (lower number = higher priority)", ge=1)]
    """Priority of the parameter for optimization (lower number = higher priority)"""
    tuning_strategy: Annotated[ParameterTuningStrategy, Field(..., description="Strategy for tuning this parameter")]
    """Strategy for tuning this parameter"""
    max_search_attempts: Annotated[int, Field(..., description="Maximum number of search attempts for this parameter", ge=1, le=20)]
    """Maximum number of search attempts for this parameter"""
    floor: Annotated[int, Field(..., description="Minimum value for the parameter during optimization", ge=1)]
    """Minimum value for the parameter during optimization"""
    operator: Annotated[Literal["+", "-", "*", "/"], Field(..., description="Operator to adjust the parameter value during optimization")]
    """Operator to adjust the parameter value during optimization"""
    modifier: Annotated[int, Field(..., description="Modifier value to apply with the operator during optimization")]
    """Modifier value to apply with the operator during optimization"""
    max_value: Annotated[int, Field(..., description="Maximum value for the parameter during optimization", ge=1)]
    """Maximum value for the parameter during optimization"""

    model_config = ConfigDict(extra="ignore")