# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class PreferencesConfig(BaseModel):
    """User preferences configuration"""
    theme: Annotated[Optional[str], Field(default='light', description="UI theme preference")] = 'light'
    """UI theme preference"""
    language: Annotated[Optional[str], Field(default='en', description="Preferred language")] = 'en'
    """Preferred language"""
    notifications_on: Annotated[Optional[bool], Field(default=True, description="Enable notifications")] = True
    """Enable notifications"""
    font_size: Annotated[Optional[int], Field(default=14, description="Font size preference")] = 14
    """Font size preference"""

    model_config = ConfigDict(extra="ignore")