# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .optimal_parameters import OptimalParameters
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class RecoveryStrategy(BaseModel):
    """Recovery strategy result with optimal parameters and strategy name"""
    parameters: Annotated[OptimalParameters, Field(..., description="Optimal parameters for the strategy")]
    """Optimal parameters for the strategy"""
    strategy_name: Annotated[Literal["clear_memory", "reduce_batch", "move_to_cpu", "reduce_context"], Field(..., description="Name of the recovery strategy applied")]
    """Name of the recovery strategy applied"""

    model_config = ConfigDict(extra="ignore")