# Code generated by schema2code at 2025-12-01 22:31:33. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class RefinementConfig(BaseModel):
    """Response refinement settings"""
    enable_response_filtering: Annotated[bool, Field(..., description="Enable response filtering")]
    """Enable response filtering"""
    enable_response_critique: Annotated[bool, Field(..., description="Enable response critique")]
    """Enable response critique"""

    model_config = ConfigDict(extra="ignore")