# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.workflow_type import WorkflowType
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class AlternativeStrategy(BaseModel):
    """Alternative routing strategy that was considered"""

    workflows: Annotated[Optional[List[str]], Field(default=None)] = None
    strategy: Annotated[Optional[str], Field(default=None)] = None
    reason: Annotated[Optional[str], Field(default=None)] = None
    confidence: Annotated[Optional[float], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")


class Metadata(BaseModel):
    """Additional metadata about the routing decision"""

    workflow_type: Annotated[
        Optional[WorkflowType],
        Field(
            default=None,
            description="Identified primary workflow type from intent analysis",
        ),
    ] = None
    """Identified primary workflow type from intent analysis"""
    complexity_level: Annotated[
        Optional[Literal["simple", "medium", "high"]],
        Field(default=None, description="Assessed complexity level"),
    ] = None
    """Assessed complexity level"""
    fallback_applied: Annotated[
        Optional[bool],
        Field(default=False, description="Whether fallback routing was applied"),
    ] = False
    """Whether fallback routing was applied"""
    routing_path: Annotated[
        Optional[List[str]],
        Field(default=None, description="Path of routing decisions taken"),
    ] = None
    """Path of routing decisions taken"""

    model_config = ConfigDict(extra="ignore")


class RoutingStrategy(BaseModel):
    """Strongly typed routing strategy result containing workflow selection and execution details"""

    selected_workflows: Annotated[
        List[str],
        Field(..., description="List of workflow names selected for execution"),
    ]
    """List of workflow names selected for execution"""
    execution_strategy: Annotated[
        Literal["single", "parallel", "series", "hybrid"],
        Field(..., description="Strategy for executing the selected workflows"),
    ]
    """Strategy for executing the selected workflows"""
    reason: Annotated[
        Literal[
            "command_based_routing",
            "explicit_routing_decision",
            "explicit_workflow_type",
            "complex_research_series",
            "multi_agent_intent",
            "creative_intent",
            "research_intent",
            "default_chat",
            "error_fallback",
        ],
        Field(..., description="Explanation for why this routing strategy was chosen"),
    ]
    """Explanation for why this routing strategy was chosen"""
    confidence: Annotated[
        Optional[float],
        Field(
            default=0.8,
            description="Confidence score for the routing decision (0.0 to 1.0)",
            ge=0.0,
            le=1.0,
        ),
    ] = 0.8
    """Confidence score for the routing decision (0.0 to 1.0)"""
    metadata: Annotated[
        Optional[Metadata],
        Field(
            default=None, description="Additional metadata about the routing decision"
        ),
    ] = None
    """Additional metadata about the routing decision"""
    target_node: Annotated[
        Optional[str],
        Field(
            default=None,
            description="Target node name for LangGraph conditional routing",
        ),
    ] = None
    """Target node name for LangGraph conditional routing"""
    alternatives: Annotated[
        Optional[List[AlternativeStrategy]],
        Field(
            default=None,
            description="Alternative routing strategies that were considered",
        ),
    ] = None
    """Alternative routing strategies that were considered"""

    model_config = ConfigDict(extra="ignore")


RoutingStrategy.model_rebuild()
