# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .dev_stats import DevStats
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class SystemGPUStats(BaseModel):
    """System-wide GPU statistics for dynamic multi-GPU systems"""
    total_gpus: Annotated[int, Field(..., description="Total number of GPU devices in the system", ge=0)]
    """Total number of GPU devices in the system"""
    total_memory: Annotated[float, Field(..., description="Total GPU memory across all devices in MB", ge=0)]
    """Total GPU memory across all devices in MB"""
    total_available_memory: Annotated[float, Field(..., description="Total available GPU memory across all devices in MB", ge=0)]
    """Total available GPU memory across all devices in MB"""
    gpus: Annotated[List[DevStats], Field(..., description="List of individual GPU device information")]
    """List of individual GPU device information"""

    model_config = ConfigDict(extra="ignore")