# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class Thought(BaseModel):
    """Represents a thought or reasoning process from an AI assistant"""
    id: Annotated[Optional[int], Field(default=None, description="Unique identifier for the thought")] = None
    """Unique identifier for the thought"""
    message_id: Annotated[Optional[int], Field(default=None, description="Foreign key reference to the associated message")] = None
    """Foreign key reference to the associated message"""
    text: Annotated[str, Field(..., description="The thinking/reasoning content")]
    """The thinking/reasoning content"""
    created_at: Annotated[Optional[datetime], Field(default=None, description="Timestamp when the thought was created")] = None
    """Timestamp when the thought was created"""

    model_config = ConfigDict(extra="ignore")