# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .resource_usage import ResourceUsage
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ToolCall(BaseModel):
    """Result from executing a tool"""
    message_id: Annotated[Optional[int], Field(default=None, description="Foreign key reference to the associated message")] = None
    """Foreign key reference to the associated message"""
    name: Annotated[str, Field(..., description="Name of the executed tool")]
    """Name of the executed tool"""
    execution_id: Annotated[Optional[str], Field(default=None, description="Unique execution identifier")] = None
    """Unique execution identifier"""
    success: Annotated[Optional[bool], Field(default=None, description="Whether execution was successful")] = None
    """Whether execution was successful"""
    args: Annotated[Dict[str, Any], Field(..., description="Arguments passed to the tool")]
    """Arguments passed to the tool"""
    result_data: Annotated[Optional[Dict[str, Any]], Field(default=None, description="Result data from the tool")] = None
    """Result data from the tool"""
    error_message: Annotated[Optional[str], Field(default=None, description="Error message if execution failed")] = None
    """Error message if execution failed"""
    execution_time_ms: Annotated[Optional[int], Field(default=None, description="Execution time in milliseconds", ge=0)] = None
    """Execution time in milliseconds"""
    resource_usage: Annotated[Optional[ResourceUsage], Field(default=None)] = None
    created_at: Annotated[Optional[datetime], Field(default=None, description="Timestamp when the tool call record was created")] = None
    """Timestamp when the tool call record was created"""

    model_config = ConfigDict(extra="ignore")