# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ToolConfig(BaseModel):
    """User-configurable tool execution settings"""
    tool_similarity_threshold: Annotated[float, Field(default=0.9, description="Similarity threshold for tool selection (0.0-1.0)", ge=0.1, le=1.0)]
    """Similarity threshold for tool selection (0.0-1.0)"""
    tool_modification_threshold: Annotated[float, Field(default=0.6, description="Threshold for tool modification/generation (0.0-1.0)", ge=0.1, le=1.0)]
    """Threshold for tool modification/generation (0.0-1.0)"""
    enable_tool_generation: Annotated[bool, Field(default=True, description="Enable dynamic tool generation")]
    """Enable dynamic tool generation"""
    max_tool_retries: Annotated[int, Field(default=3, description="Maximum retries for failed tool executions", ge=0, le=10)]
    """Maximum retries for failed tool executions"""
    tool_timeout: Annotated[float, Field(default=30.0, description="Default tool execution timeout in seconds", ge=1.0, le=120.0)]
    """Default tool execution timeout in seconds"""
    enable_tool_caching: Annotated[bool, Field(default=True, description="Enable tool result caching")]
    """Enable tool result caching"""
    tool_cache_ttl: Annotated[int, Field(default=1800, description="Tool cache TTL in seconds", ge=60, le=7200)]
    """Tool cache TTL in seconds"""
    enable_semantic_search: Annotated[bool, Field(default=True, description="Enable semantic tool selection")]
    """Enable semantic tool selection"""
    search_top_k: Annotated[int, Field(default=10, description="Number of top tools to consider in semantic search", ge=1, le=50)]
    """Number of top tools to consider in semantic search"""

    model_config = ConfigDict(extra="ignore")