# Code generated by schema2code at 2026-03-07 19:34:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from models.circuit_breaker_config import CircuitBreakerConfig
from models.crash_prevention import CrashPrevention
from models.event_stream_config import EventStreamConfig
from models.gpu_config import GPUConfig
from models.image_generation_config import ImageGenerationConfig
from models.memory_config import MemoryConfig
from models.model_profile_config import ModelProfileConfig
from models.parameter_optimization_config import ParameterOptimizationConfig
from models.parameter_tuning_strategy import ParameterTuningStrategy
from models.performance_parameter import PerformanceParameter
from models.preferences_config import PreferencesConfig
from models.summarization_config import SummarizationConfig
from models.tool_config import ToolConfig
from models.workflow_config import WorkflowConfig
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat


class UserConfig(BaseModel):
    """User-specific configuration"""

    user_id: Annotated[str, Field(..., description="User ID")]
    """User ID"""
    summarization: Annotated[Optional[SummarizationConfig], Field(default=None)] = None
    memory: Annotated[Optional[MemoryConfig], Field(default=None)] = None
    model_profiles: Annotated[Optional[ModelProfileConfig], Field(default=None)] = None
    image_generation: Annotated[
        Optional[ImageGenerationConfig], Field(default=None)
    ] = None
    circuit_breaker: Annotated[CircuitBreakerConfig, Field(...)]
    gpu_config: Annotated[GPUConfig, Field(...)]
    parameter_optimization: Annotated[ParameterOptimizationConfig, Field(...)]
    workflow: Annotated[WorkflowConfig, Field(...)]
    tool: Annotated[Optional[ToolConfig], Field(default=None)] = None
    event_stream: Annotated[Optional[EventStreamConfig], Field(default=None)] = None
    preferences: Annotated[Optional[PreferencesConfig], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore", protected_namespaces=())
